### ISSUE TITLE
[Static install] Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH

### ISSUE THREAD

**Issue by cruscio** [89luca89/distrobox#667]
After running `install-podman` from [Install Podman in a static manner](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#install-podman-in-a-static-manner) on a SteamDeck, `podman pod create` fails

```
$ podman --log-level debug pod create
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called create.PersistentPreRunE(podman --log-level debug pod create) 
DEBU[0000] Found default OCI runtime /home/deck/.local/podman/bin/crun path via PATH environment variable 
DEBU[0000] Merged system config "/home/deck/.config/containers/containers.conf" 
DEBU[0000] Using conmon: "/home/deck/.local/podman/lib/podman/conmon" 
DEBU[0000] Initializing boltdb state at /home/deck/.local/podman/share/podman/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/deck/.local/podman/lib/containers/storage 
DEBU[0000] Using run root /home/deck/.local/podman/run/containers/storage 
DEBU[0000] Using static dir /home/deck/.local/podman/share/podman/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/deck/.local/podman/share/podman/volume 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: ignore_chown_errors=true            
DEBU[0000] overlay: mount_program=/home/deck/.local/podman/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file              
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/home/deck/.local/podman/bin/crun" 
INFO[0000] Setting parallel job count to 25             
DEBU[0000] Looking up image "localhost/podman-pause:4.2.1-0" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "localhost/podman-pause:4.2.1-0" ...  
DEBU[0000] Trying "localhost/podman-pause:4.2.1-0" ...  
DEBU[0000] Trying "localhost/podman-pause:4.2.1-0" ...  
Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH

$ podman --version
podman version 4.2.1
```

Looks like this may be getting fixed upstream by changing what pause container is used:
* [container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory · Issue #54 · mgoltzsche/podman-static](https://github.com/mgoltzsche/podman-static/issues/54)
* [fix: configure infra\_image by default by mgoltzsche · Pull Request #55 · mgoltzsche/podman-static](https://github.com/mgoltzsche/podman-static/pull/55)

**Comment by cruscio** [comment]
Workaround: add `infra_image="k8s.gcr.io/pause:3.8"` to `/home/deck/.config/containers/containers.conf` in the `[engine]` section, and run `podman pull k8s.gcr.io/pause:3.8`

**Comment by willzhang** [comment]
> 

it's not work
```
root@node01:~# cat  /etc/containers/containers.conf
# See https://github.com/containers/common/blob/master/pkg/config/containers.conf
[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
infra_image="k8s.gcr.io/pause:3.8"
root@node01:~# podman pull k8s.gcr.io/pause:3.8
Trying to pull k8s.gcr.io/pause:3.8...
Getting image source signatures
Copying blob 9457426d6899 done  
Copying config 4873874c08 done  
Writing manifest to image destination
Storing signatures
4873874c08efc72e9729683a83ffbb7502ee729e9a5ac097723806ea7fa13517
root@node01:~# cephadm bootstrap --mon-ip 192.168.72.40
Verifying podman|docker is present...
Verifying lvm2 is present...
Verifying time synchronization is in place...
Unit chrony.service is enabled and running
Repeating the final host check...
podman (/usr/local/bin/podman) version 4.4.3 is present
systemctl is present
lvcreate is present
Unit chrony.service is enabled and running
Host looks OK
Cluster fsid: aac503de-d174-11ed-bad6-d1da98c13f11
Verifying IP 192.168.72.40 port 3300 ...
Verifying IP 192.168.72.40 port 6789 ...
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Pulling container image quay.io/ceph/ceph:v17...
Non-zero exit code 125 from /usr/local/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint ceph --init -e CONTAINER_IMAGE=quay.io/ceph/ceph:v17 -e NODE_NAME=node01 -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph:v17 --version
ceph: stderr Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/cephadm", line 9653, in <module>
    main()
  File "/usr/local/bin/cephadm", line 9641, in main
    r = ctx.func(ctx)
  File "/usr/local/bin/cephadm", line 2205, in _default_image
    return func(ctx)
  File "/usr/local/bin/cephadm", line 5664, in command_bootstrap
    image_ver = CephContainer(ctx, ctx.image, 'ceph', ['--version']).run().strip()
  File "/usr/local/bin/cephadm", line 4144, in run
    out, _, _ = call_throws(self.ctx, self.run_cmd(),
  File "/usr/local/bin/cephadm", line 1852, in call_throws
    raise RuntimeError(f'Failed command: {" ".join(command)}: {s}')
RuntimeError: Failed command: /usr/local/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint ceph --init -e CONTAINER_IMAGE=quay.io/ceph/ceph:v17 -e NODE_NAME=node01 -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph:v17 --version: Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory

root@node01:~# 
```

**Comment by 89luca89** [comment]
Added the config to the file :+1:
